adding decimal point and retraction for keyboard
mxc-foundation/supernode-app pull request #272
Opened 2021-07-09 15:14 UTC by zhbh

This branch has solved two issues as follow:
1. Keyboard in unbond DHX screen does not go away once you bring it up #266
2. Keyboard in unbond DHX screen needs a decimal point #265

2021-07-12 10:01 UTC, festelo requested changes

2021-07-12 10:01 UTC, festelo commented on lib/page/home_page/wallet/supernode_dhx_token/dhx_bonding_page.dart
> +              ])),
commas

2021-07-12 10:01 UTC, festelo commented on lib/page/home_page/wallet/supernode_dhx_token/dhx_unbonding_page.dart
> +          onTap: () => FocusScope.of(context).requestFocus(FocusNode()),
see the comment above about focusNode

2021-07-12 10:01 UTC, festelo commented on lib/page/home_page/wallet/supernode_dhx_token/dhx_unbonding_page.dart
> +              ])),
commas

2021-07-14 08:43 UTC, zhbh commented on lib/page/home_page/wallet/supernode_dhx_token/dhx_bonding_page.dart
> +          onTap: () => FocusScope.of(context).requestFocus(FocusNode()),
Okay, Thanks.

2021-07-14 10:01 UTC, zhbh commented on lib/page/home_page/wallet/supernode_dhx_token/dhx_bonding_page.dart
> +                                                  new TapGestureRecognizer()
Someone uses, I will delete that.

2021-07-14 10:02 UTC, zhbh commented on lib/page/home_page/wallet/supernode_dhx_token/dhx_bonding_page.dart
> +                                                                .supernodeDhx)),
What?

2021-07-14 10:07 UTC, zhbh commented on lib/page/home_page/wallet/supernode_dhx_token/dhx_bonding_page.dart
> +          onTap: () => FocusScope.of(context).requestFocus(FocusNode()),
I search requestFocus in the project, which many places use likes that. And I replace all with unfocus().

2021-07-14 10:17 UTC, zhbh commented on lib/page/home_page/wallet/supernode_dhx_token/dhx_bonding_page.dart
> +                                                                .supernodeDhx)),
IDE can add comma automatically at the end of statement. So Flutter format can't make it well.

2021-07-14 10:17 UTC, zhbh commented on lib/page/home_page/wallet/supernode_dhx_token/dhx_bonding_page.dart
> +                                                            })),
delete commas

2021-07-14 10:24 UTC, zhbh commented on lib/page/home_page/wallet/supernode_dhx_token/dhx_bonding_page.dart
> +                                                                .supernodeDhx)),
delete commas

2021-07-14 10:47 UTC, merged