Sam/future/mmd 1291/fuel stats widget
mxc-foundation/supernode-app pull request #274
Opened 2021-07-12 05:47 UTC by jeffstahlnecker

2021-07-12 09:52 UTC, festelo requested changes

2021-07-12 09:52 UTC, festelo commented on lib/common/components/summary_row.dart
> +      Visibility(
can we use `if (image != null && image.isNotEmpty)` construction instead of `Visibility` widget? It's less expensive.

2021-07-12 09:52 UTC, festelo commented on lib/common/components/summary_row.dart
> +                  image,
That will be good if we will have image param with type `ImageProvider`, not `String`. In this case we will have more movement to reuse widget - because we can use `AssetImage`, `NetworkImage`, `FileImage`, etc. and we are not limited to just AssetImage.
But if you sure we don't need it, it's ok.

2021-07-12 09:52 UTC, festelo commented on lib/common/components/widgets/circular_graph.dart
> +  double size = 200.0;
Fields in widgets should not be mutable, so it must stay `final`. Only states can have mutable fields. Widget is recreated with every `build` method call (that potentially can be called for every frame), while state of widget lives longer - until the widget completely unattached from widget tree.

2021-07-12 09:52 UTC, festelo commented on lib/page/home_page/user/view.dart
> +              ))),
If you insert commas between brackets, they will be moved on separated lines by dart format tool. I think with commas it looks better and flutter itself doesn't spare commas in source code, but it's up to you.

2021-07-12 09:52 UTC, festelo commented on lib/page/home_page/user/view.dart
> +                  : fuelColor),
looks expensive. Probably better to move outside of `return` clause.
Like this:
```
var percentageValue = (percentage ?? 0) * 100; // can we use default param value? double percentage = 0, in method signature
Color color;
if (loading || amount != null) { 
  color = Colors.grey;
}
else if (percentageValue > 10) {
color = minerColor; 
}
else {
color = fuelColor;
}
```

2021-07-12 10:11 UTC, zhbh commented on lib/common/components/summary_row.dart
> +      Visibility(
I think it also doesn't take a lot of time for it if it is used on a single page.

2021-07-12 10:29 UTC, festelo commented on lib/common/components/summary_row.dart
> +      Visibility(
Yeah, but if we can avoid this - why not.

2021-07-12 12:57 UTC, festelo commented on lib/common/components/summary_row.dart
> +                  image,
And that's also more clear. When you see "String image" nothing says you that this is asset image path, you need to check sources to get it.

2021-07-13 10:57 UTC, zhbh commented on lib/page/home_page/user/view.dart
> +              ))),
this commas automatically is added by IDE.

2021-07-13 11:08 UTC, miljan-mxc commented on lib/common/components/widgets/circular_graph.dart
> +  CircularGraph(this.percentage, this.graphColor, {this.child = defaultWidget, this.size = 200, this.paddingSize = 17.0, this.lineWidth = 20.0});
can size, paddingSize, lineWidth be used as default values here?

2021-07-13 11:13 UTC, miljan-mxc commented on lib/page/home_page/user/view.dart
> +                                ? '-- MXC'
Suggestion to use Token.MXC.name instead of hardcoded MXC

2021-07-13 11:15 UTC, miljan-mxc approved these changes

2021-07-13 11:40 UTC, festelo commented on lib/page/home_page/user/view.dart
> +              ))),
yeah, i'm not against commas, i think with them code looks better.

2021-07-13 11:40 UTC, festelo approved these changes

2021-07-14 04:15 UTC, merged